from concurrent.futures import ThreadPoolExecutor

import pytest

from hub.bootstrap import create_app, start_platform_worker
from hub.config import FleetConfig
from hub.infrastructure.platform_db import PlatformRepository


OWNER = "owner@example.test"


def _app(tmp_path, *, worker=False, owner=OWNER, memory=False, memory_context=False):
    return create_app(FleetConfig.from_root(
        tmp_path, ingest_token="x", dev_operator=owner,
        platform_enabled=True, platform_worker_enabled=worker,
        platform_memory_enabled=memory,
        platform_memory_context_enabled=memory_context,
    ))


def _catalog(app, tmp_path, *, backend="directory", owner=OWNER):
    repo = app.extensions["fleet"]["platform_repository"]
    repo.upsert_model(owner, {"profile_id": "local", "provider": "deterministic", "model": "local"})
    repo.upsert_workspace(owner, {
        "workspace_id": "home", "backend": backend,
        "root_path": str(tmp_path / "workspace"),
    })
    repo.update_defaults(owner, {
        "model_profile_id": "local", "workspace_id": "home",
    }, 0)
    return repo


def _queued(app, client_token="turn-1", owner=OWNER):
    client = app.test_client()
    conversation = client.post("/api/platform/v1/conversations", json={}).get_json()["conversation"]
    return client.post(
        f"/api/platform/v1/conversations/{conversation['conversation_id']}/turns",
        json={"text": "写一个报告", "client_token": client_token},
    ).get_json()["run"]


def test_worker_claims_and_finishes_local_run_with_events(tmp_path):
    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    run = _queued(app)
    worker = app.extensions["fleet"]["services"]["platform_worker"]

    result = worker.run_once(OWNER)

    assert result["state"] == "succeeded"
    assert (tmp_path / "workspace" / "assistant-report.md").read_text() == "Generated by the assistant.\n"
    client = app.test_client()
    assert client.get(f"/api/platform/v1/runs/{run['run_id']}").get_json()["state"] == "succeeded"
    events = client.get(f"/api/platform/v1/runs/{run['run_id']}/events").get_json()["events"]
    assert [event["kind"] for event in events] == ["run_started", "tool_call", "tool_result", "run_finished"]


@pytest.mark.parametrize('remote', [False, True])
@pytest.mark.parametrize('tool', ['workspace.list', 'workspace.write', 'workspace.artifact', 'workspace.exec'])
def test_acceptance_policy_is_frozen_and_enforced_by_new_worker(tmp_path, remote, tool):
    from hub.application.run_worker_service import LocalRunWorkerService
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path)
    repo = _catalog(app, tmp_path)
    (tmp_path / 'workspace').mkdir()
    target = tmp_path / 'workspace' / 'flow.txt'
    target.write_bytes(b'preserved')
    overrides = {'tool_policy': 'unrestricted', 'allowed_tools': [tool]}
    if remote:
        repo.upsert_node(OWNER, {'node_id': 'remote', 'label': 'remote'})
        overrides['execution_node_id'] = 'remote'
    client = app.test_client()
    conversation = client.post('/api/platform/v1/conversations', json={'workspace_id': 'home'}).get_json()['conversation']
    path = f"/api/platform/v1/conversations/{conversation['conversation_id']}"
    body = {'text': 'inspect', 'client_token': 'acceptance-policy', 'overrides': overrides}
    response = client.post(path + '/acceptance-turns', json=body)
    assert response.status_code == 202
    run_id = response.get_json()['run']['run_id']
    assert repo.get_run(OWNER, run_id)['config_snapshot']['tool_policy'] == 'acceptance_read_only'
    assert client.post(path + '/acceptance-turns', json=body).get_json()['run']['run_id'] == run_id
    assert client.post(path + '/turns', json=body).status_code == 409

    declarations, commands = [], []

    class Provider:
        def complete(self, messages, tools):
            declarations.append([item['name'] for item in tools])
            if len(declarations) > 1:
                return ModelResponse(kind='final', text='done')
            arguments = {'path': 'flow.txt', 'content': 'overwritten'} if tool == 'workspace.write' else {}
            return ModelResponse(kind='tool_call', tool=tool, arguments=arguments)

    class Delivery:
        def enqueue(self, command, **kwargs):
            commands.append(command.action)

        def wait_for_receipt(self, *args, **kwargs):
            return {'status': 'succeeded', 'result': {}}

    # A fresh service has only the persisted Run snapshot, no CLI/request state.
    worker = LocalRunWorkerService(repo, app.extensions['fleet']['services']['run_events'],
        provider_factory=lambda profile: Provider(), remote_execution_enabled=True,
        remote_delivery=Delivery())
    result = worker.run_once(OWNER)
    assert result['state'] == ('succeeded' if tool == 'workspace.list' else 'failed')
    assert all(names == ['workspace.list'] for names in declarations)
    assert commands == (['tool.workspace.list'] if remote and tool == 'workspace.list' else [])
    assert target.read_bytes() == b'preserved'
    events = client.get(f'/api/platform/v1/runs/{run_id}/events').get_json()['events']
    receipt = next(e['payload'] for e in events if e['kind'] == 'tool_result')
    if tool != 'workspace.list':
        assert receipt['error_code'] == 'tool_not_allowed'


@pytest.mark.parametrize('race', [False, True])
def test_acceptance_cannot_reuse_unrestricted_turn_token(tmp_path, monkeypatch, race):
    app = _app(tmp_path)
    _catalog(app, tmp_path)
    run = _queued(app)
    if race:
        repo = app.extensions['fleet']['platform_repository']
        original = repo.get_conversation

        def stale_conversation(*args, **kwargs):
            return {**original(*args, **kwargs), 'messages': [], 'runs': []}

        monkeypatch.setattr(repo, 'get_conversation', stale_conversation)
    response = app.test_client().post(
        f"/api/platform/v1/conversations/{run['conversation_id']}/acceptance-turns",
        json={'text': '写一个报告', 'client_token': 'turn-1'},
    )
    assert response.status_code == 409


def test_worker_injects_frozen_memory_and_journals_redacted_evidence(tmp_path):
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True, memory=True, memory_context=True)
    _catalog(app, tmp_path)
    memory_repo = app.extensions["fleet"]["repositories"]["platform_memory"]
    memory_repo.create(OWNER, {
        "memory_id": "memory-worker", "kind": "note", "title": "Worker note",
        "content": "Use the stable workspace.", "tags": ["run"],
    }, now=1)
    client = app.test_client()
    conversation = client.post("/api/platform/v1/conversations", json={}).get_json()["conversation"]
    run = client.post(
        f"/api/platform/v1/conversations/{conversation['conversation_id']}/turns",
        json={
            "text": "summarize", "client_token": "worker-memory",
            "memory_context": {
                "enabled": True, "memory_ids": ["memory-worker"],
                "max_items": 1, "max_bytes": 512,
            },
        },
    ).get_json()["run"]

    class Provider:
        def __init__(self):
            self.messages = []

        def complete(self, messages, tools):
            self.messages.append(messages)
            return ModelResponse(kind="final", text="done")

    provider = Provider()
    worker = app.extensions["fleet"]["services"]["platform_worker"]
    worker.provider_factory = lambda profile: provider
    assert worker.run_once(OWNER)["state"] == "succeeded"

    first_messages = provider.messages[0]
    assert first_messages[0]["role"] == "system"
    assert "Use the stable workspace." in first_messages[0]["content"]
    assert len(first_messages[0]["content"].encode("utf-8")) <= 512
    assert first_messages[1]["role"] == "user"
    events = client.get(f"/api/platform/v1/runs/{run['run_id']}/events").get_json()["events"]
    selected = next(event for event in events if event["kind"] == "memory_context_selected")
    assert selected["payload"]["memory_ids"] == ["memory-worker"]
    assert selected["payload"]["item_count"] == 1
    assert "Use the stable workspace." not in str(selected)


def test_worker_uses_snapshot_after_live_memory_changes(tmp_path):
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True, memory=True, memory_context=True)
    _catalog(app, tmp_path)
    memory_repo = app.extensions["fleet"]["repositories"]["platform_memory"]
    memory_repo.create(OWNER, {
        "memory_id": "memory-retry", "kind": "note", "title": "Retry note",
        "content": "Original frozen value.",
    }, now=1)
    client = app.test_client()
    conversation = client.post("/api/platform/v1/conversations", json={}).get_json()["conversation"]
    run = client.post(
        f"/api/platform/v1/conversations/{conversation['conversation_id']}/turns",
        json={
            "text": "retry", "client_token": "retry-memory",
            "memory_context": {
                "enabled": True, "memory_ids": ["memory-retry"],
                "max_items": 1, "max_bytes": 512,
            },
        },
    ).get_json()["run"]
    memory_repo.update(OWNER, "memory-retry", {"content": "Changed live value."}, expected_revision=0, now=2)

    class Provider:
        def __init__(self): self.messages = []

        def complete(self, messages, tools):
            self.messages.append(messages)
            return ModelResponse(kind="final", text="done")

    provider = Provider()
    worker = app.extensions["fleet"]["services"]["platform_worker"]
    worker.provider_factory = lambda profile: provider
    assert worker.run_once(OWNER)["state"] == "succeeded"
    assert "Original frozen value." in provider.messages[0][0]["content"]
    assert "Changed live value." not in provider.messages[0][0]["content"]


def test_worker_artifact_is_listed_and_downloadable_in_conversation_workspace(tmp_path):
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    repo = app.extensions["fleet"]["platform_repository"]
    conversation = repo.create_conversation(OWNER, "conv-artifact", title="", workspace_id="home")
    repo.append_turn(
        OWNER, conversation["conversation_id"], "msg-artifact", "run-artifact",
        text="生成产物", client_token="artifact-turn",
        config_snapshot={"workspace_id": "home", "model_profile_id": "local"}, now=1,
    )

    class Provider:
        def __init__(self):
            self.calls = 0

        def complete(self, messages, tools):
            self.calls += 1
            if self.calls == 1:
                return ModelResponse(
                    kind="tool_call", tool="workspace.write",
                    arguments={"path": "report.md", "content": "artifact body"},
                )
            if self.calls == 2:
                return ModelResponse(
                    kind="tool_call", tool="workspace.artifact",
                    arguments={"path": "report.md", "name": "report.md"},
                )
            return ModelResponse(kind="final", text="已生成")

    worker = app.extensions["fleet"]["services"]["platform_worker"]
    worker.provider_factory = lambda profile: Provider()
    assert worker.run_once(OWNER)["state"] == "succeeded"

    client = app.test_client()
    listed = client.get("/api/platform/v1/workspaces/home/artifacts")
    assert listed.status_code == 200
    artifacts = listed.get_json()["artifacts"]
    assert len(artifacts) == 1
    content = client.get(
        f"/api/platform/v1/artifacts/{artifacts[0]['artifact_id']}/content?workspace_id=home"
    )
    assert content.status_code == 200
    assert content.data == b"artifact body"


def test_worker_gate_is_default_off_and_lifecycle_is_explicit(tmp_path):
    disabled = _app(tmp_path)
    assert "platform_worker" not in disabled.extensions["fleet"]["services"]
    with pytest.raises(RuntimeError, match="disabled"):
        start_platform_worker(disabled)

    enabled = _app(tmp_path / "enabled", worker=True)
    stop = start_platform_worker(enabled, interval_s=0.1)
    stop()


def test_two_workers_only_one_claims_a_queued_run(tmp_path):
    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    _queued(app)
    repository = app.extensions["fleet"]["platform_repository"]
    events = app.extensions["fleet"]["services"]["run_events"]
    from hub.application.run_worker_service import LocalRunWorkerService

    workers = [
        LocalRunWorkerService(repository, events, worker_id="worker-a"),
        LocalRunWorkerService(repository, events, worker_id="worker-b"),
    ]
    with ThreadPoolExecutor(max_workers=2) as pool:
        results = list(pool.map(lambda item: item.run_once(OWNER), workers))
    assert sum(item is not None for item in results) == 1
    assert sum(item is not None and item.get("state") == "succeeded" for item in results) == 1


def test_expired_run_lease_can_be_reclaimed_by_new_worker(tmp_path):
    repository = PlatformRepository(tmp_path / "platform.db")
    repository.init()
    repository.upsert_workspace(OWNER, {"workspace_id": "home", "root_path": str(tmp_path / "home")})
    repository.upsert_model(OWNER, {"profile_id": "local", "provider": "deterministic", "model": "local"})
    conversation = repository.create_conversation(OWNER, "conv-1", title="", workspace_id="home")
    repository.append_turn(OWNER, conversation["conversation_id"], "msg-1", "run-1", text="x", client_token="x", config_snapshot={"workspace_id": "home", "model_profile_id": "local"}, now=1)
    first = repository.claim_run(OWNER, worker_id="worker-a", now=2, lease_s=5)
    second = repository.claim_run(OWNER, worker_id="worker-b", now=3, lease_s=5)
    reclaimed = repository.claim_run(OWNER, worker_id="worker-b", now=8, lease_s=5)

    assert first["attempt"] == 1
    assert second is None
    assert reclaimed["attempt"] == 2
    assert reclaimed["lease_id"] != first["lease_id"]


def test_worker_is_owner_scoped(tmp_path):
    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    _queued(app)
    worker = app.extensions["fleet"]["services"]["platform_worker"]
    assert worker.run_once("other@example.test") is None
    assert app.test_client().get("/api/platform/v1/runs/does-not-exist").status_code == 404


def test_missing_workspace_and_unknown_backend_fail_closed(tmp_path):
    app = _app(tmp_path, worker=True)
    repo = app.extensions["fleet"]["platform_repository"]
    repo.upsert_model(OWNER, {"profile_id": "local", "provider": "deterministic", "model": "local"})
    conversation = repo.create_conversation(OWNER, "conv-1", title="", workspace_id=None)
    repo.append_turn(OWNER, conversation["conversation_id"], "msg-1", "run-1", text="x", client_token="x", config_snapshot={"model_profile_id": "local"}, now=1)
    worker = app.extensions["fleet"]["services"]["platform_worker"]
    assert worker.run_once(OWNER)["state"] == "failed"
    assert repo.get_run(OWNER, "run-1")["state"] == "failed"

    app2 = _app(tmp_path / "other", worker=True)
    _catalog(app2, tmp_path / "other", backend="unsupported")
    _queued(app2, client_token="backend-1")
    assert app2.extensions["fleet"]["services"]["platform_worker"].run_once(OWNER)["state"] == "failed"


def test_compatible_profile_does_not_fall_back_to_deterministic_provider(tmp_path):
    app = _app(tmp_path, worker=True)
    repo = app.extensions["fleet"]["platform_repository"]
    repo.upsert_model(OWNER, {
        "profile_id": "remote", "provider": "compatible", "model": "configured-model",
    })
    repo.upsert_workspace(OWNER, {
        "workspace_id": "home", "root_path": str(tmp_path / "workspace"),
    })
    conversation = repo.create_conversation(
        OWNER, "conv-remote", title="", workspace_id="home")
    repo.append_turn(
        OWNER, conversation["conversation_id"], "msg-remote", "run-remote",
        text="hello", client_token="remote-provider",
        config_snapshot={"workspace_id": "home", "model_profile_id": "remote"}, now=1,
    )

    result = app.extensions["fleet"]["services"]["platform_worker"].run_once(OWNER)

    assert result["state"] == "failed"
    assert repo.get_run(OWNER, "run-remote")["result_text"] == "provider_unavailable"
    assert not (tmp_path / "workspace" / "assistant-report.md").exists()


def test_cancel_is_observed_before_next_model_step(tmp_path):
    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    run = _queued(app)
    worker = app.extensions["fleet"]["services"]["platform_worker"]
    original = worker.provider_factory

    class Provider:
        def __init__(self, repository):
            self.repository = repository
            self.calls = 0

        def complete(self, messages, tools):
            self.calls += 1
            if self.calls == 1:
                self.repository.cancel_run(OWNER, run["run_id"], now=2)
            from tools.platform.providers.base import ModelResponse
            return ModelResponse(kind="final", text="should be cancelled")

    worker.provider_factory = lambda profile: Provider(worker.repository)
    result = worker.run_once(OWNER)
    assert result["state"] == "cancelled"
    assert app.test_client().get(f"/api/platform/v1/runs/{run['run_id']}").get_json()["state"] == "cancelled"


def test_remote_run_uses_node_delivery_without_local_filesystem(tmp_path):
    from hub.application.run_worker_service import LocalRunWorkerService
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path)
    repo = app.extensions["fleet"]["platform_repository"]
    repo.upsert_node(OWNER, {"node_id": "node-remote", "label": "remote"})
    repo.upsert_model(OWNER, {"profile_id": "local", "provider": "deterministic", "model": "local"})
    repo.upsert_workspace(OWNER, {
        "workspace_id": "home", "root_path": str(tmp_path / "workspace"),
    })
    conversation = repo.create_conversation(OWNER, "conv-remote", title="", workspace_id="home")
    repo.append_turn(OWNER, conversation["conversation_id"], "msg-remote", "run-remote",
                     text="read", client_token="remote",
                     config_snapshot={"workspace_id": "home", "model_profile_id": "local",
                                      "execution_node_id": "node-remote"}, now=1)

    class Provider:
        def __init__(self):
            self.calls = 0

        def complete(self, messages, tools):
            self.calls += 1
            if self.calls == 1:
                return ModelResponse(kind="tool_call", tool="workspace.read",
                                     arguments={"path": "report.md"})
            return ModelResponse(kind="final", text="done")

    class Delivery:
        def __init__(self):
            self.commands = []

        def enqueue(self, command, *, idempotency_key=None):
            self.commands.append(command)
            return command.as_dict()

        def wait_for_receipt(self, command_id, *, timeout_s=30.0):
            return {"command_id": command_id, "status": "succeeded",
                    "result": {"content": "remote"}}

    delivery = Delivery()
    worker = LocalRunWorkerService(
        repo, app.extensions["fleet"]["services"]["run_events"],
        worker_id="remote-worker", provider_factory=lambda profile: Provider(),
        remote_execution_enabled=True, remote_delivery=delivery,
    )
    result = worker.run_once(OWNER)

    assert result["state"] == "succeeded"
    assert [command.action for command in delivery.commands] == ["tool.workspace.read"]
    assert not (tmp_path / "workspace" / "assistant-report.md").exists()
    kinds = [event["kind"] for event in app.extensions["fleet"]["services"]["run_events"].list(OWNER, "run-remote")["events"]]
    assert kinds == ["run_started", "tool_call", "node_command_queued", "node_receipt", "tool_result", "run_finished"]


def test_remote_unknown_receipt_finishes_run_unknown_without_replay(tmp_path):
    from hub.application.run_worker_service import LocalRunWorkerService
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path)
    repo = app.extensions["fleet"]["platform_repository"]
    repo.upsert_node(OWNER, {"node_id": "node-remote", "label": "remote"})
    repo.upsert_model(OWNER, {"profile_id": "local", "provider": "deterministic", "model": "local"})
    repo.upsert_workspace(OWNER, {"workspace_id": "home", "root_path": str(tmp_path / "workspace")})
    conversation = repo.create_conversation(OWNER, "conv-unknown", title="", workspace_id="home")
    repo.append_turn(OWNER, conversation["conversation_id"], "msg-unknown", "run-unknown",
                     text="write", client_token="unknown",
                     config_snapshot={"workspace_id": "home", "model_profile_id": "local",
                                      "execution_node_id": "node-remote"}, now=1)

    class Provider:
        def complete(self, messages, tools):
            return ModelResponse(kind="tool_call", tool="workspace.write",
                                 arguments={"path": "report.md", "content": "x"})

    class Delivery:
        def __init__(self): self.commands = []
        def enqueue(self, command, *, idempotency_key=None):
            self.commands.append(command); return command.as_dict()
        def wait_for_receipt(self, command_id, *, timeout_s=30.0):
            return {"command_id": command_id, "status": "unknown",
                    "result": {"reason": "receipt_timeout"}}

    delivery = Delivery()
    worker = LocalRunWorkerService(
        repo, app.extensions["fleet"]["services"]["run_events"],
        worker_id="unknown-worker", provider_factory=lambda profile: Provider(),
        remote_execution_enabled=True, remote_delivery=delivery,
    )
    assert worker.run_once(OWNER)["state"] == "unknown"
    assert len(delivery.commands) == 1
    assert repo.get_run(OWNER, "run-unknown")["state"] == "unknown"


def test_default_worker_rejects_unsandboxed_host_exec(tmp_path):
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    run = _queued(app)
    outside = tmp_path / 'outside-secret.txt'
    outside.write_text('host-only-sentinel')

    class Provider:
        def complete(self, messages, tools):
            if len(messages) > 1:
                return ModelResponse(kind='final', text=str(messages[-1]))
            return ModelResponse(kind='tool_call', tool='workspace.exec',
                                 arguments={'argv': ['cat', str(outside)]})

    worker = app.extensions['fleet']['services']['platform_worker']
    worker.provider_factory = lambda profile: Provider()
    result = worker.run_once(OWNER)
    assert result['state'] == 'failed'
    events = worker.run_events.list(OWNER, run['run_id'])['events']
    receipt = next(e['payload'] for e in events if e['kind'] == 'tool_result')
    assert receipt['error_code'] == 'sandbox_unavailable'
    assert 'host-only-sentinel' not in str(result) + str(events)


@pytest.mark.parametrize('cancelled', [False, True])
@pytest.mark.parametrize('crash_phase', ['after_publication', 'after_receipt'])
def test_expired_started_run_is_unknown_without_replaying_side_effect(tmp_path, monkeypatch, cancelled, crash_phase):
    from hub.application.run_worker_service import LocalRunWorkerService
    from hub.application.run_event_service import RunEventService
    from tools.platform.artifacts import ArtifactStore
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True)
    repo = _catalog(app, tmp_path)
    run = _queued(app)
    workspace = tmp_path / 'workspace'
    workspace.mkdir(exist_ok=True)
    (workspace / 'result.txt').write_text('completed effect')
    artifacts = ArtifactStore(tmp_path / 'artifacts')
    now = [10.0]
    if crash_phase == 'after_publication':
        original_put = artifacts.put_file
        def publish_then_die(*args, **kwargs):
            original_put(*args, **kwargs)
            raise SystemExit('process died before tool receipt')
        monkeypatch.setattr(artifacts, 'put_file', publish_then_die)

    class Provider:
        def complete(self, messages, tools):
            if any(m['role'] == 'tool' for m in messages):
                raise SystemExit('process died after artifact publication')
            return ModelResponse(kind='tool_call', tool='workspace.artifact',
                                 arguments={'path': 'result.txt', 'name': 'result.txt'})

    def worker(repository):
        return LocalRunWorkerService(
            repository, RunEventService(repository, clock=lambda: now[0]),
            lease_s=5, clock=lambda: now[0], artifact_store=artifacts,
            provider_factory=lambda profile: Provider())

    with pytest.raises(SystemExit):
        worker(repo).run_once(OWNER)
    assert len(artifacts.list(OWNER, 'home')) == 1
    if cancelled:
        repo.cancel_run(OWNER, run['run_id'], now=11)
    now[0] = 20.0
    restarted_repo = PlatformRepository(repo.db_path)
    restarted_repo.init()
    from hub.application.run_scheduler_service import RunSchedulerService
    restarted_worker = worker(restarted_repo)
    scheduler = RunSchedulerService(restarted_repo, restarted_worker, clock=lambda: now[0])
    recovered = scheduler.tick_once()
    assert recovered['state'] == 'unknown'
    assert len(artifacts.list(OWNER, 'home')) == 1
    assert worker(restarted_repo).run_once(OWNER) is None
    events = restarted_repo.list_run_events(OWNER, run['run_id'])['events']
    assert sum(e['kind'] == 'run_started' for e in events) == 1
    assert events[-1]['kind'] == 'run_unknown'


def test_queued_turns_use_trigger_cutoff_and_durable_assistant_history(tmp_path):
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True)
    repo = _catalog(app, tmp_path)
    repo.create_conversation(OWNER, 'conv-order', title='', workspace_id='home')
    for message_id, run_id, text in [('msg-z', 'run-z', 'FIRST'), ('msg-a', 'run-a', 'SECOND')]:
        repo.append_turn(OWNER, 'conv-order', message_id, run_id, text=text,
                         client_token=text, config_snapshot={'workspace_id': 'home', 'model_profile_id': 'local'}, now=1)
    assert [m['content'] for m in repo.get_run_execution_context(OWNER, 'run-z')['messages']] == ['FIRST']
    captured = []

    class Provider:
        def complete(self, messages, tools):
            captured.append([(m['role'], m['content']) for m in messages])
            return ModelResponse(kind='final', text='ANSWER-' + messages[-1]['content'])

    worker = app.extensions['fleet']['services']['platform_worker']
    worker.provider_factory = lambda profile: Provider()
    assert worker.run_once(OWNER)['run_id'] == 'run-z'
    # Reopen the repository, so history cannot come from worker memory.
    worker.repository = PlatformRepository(repo.db_path)
    worker.repository.init()
    assert worker.run_once(OWNER)['run_id'] == 'run-a'
    assert captured == [[('user', 'FIRST')], [('user', 'FIRST'), ('assistant', 'ANSWER-FIRST'), ('user', 'SECOND')]]
    messages = repo.get_conversation(OWNER, 'conv-order')['messages']
    assert [(m['role'], m['content']) for m in messages] == captured[1] + [('assistant', 'ANSWER-SECOND')]
    assert [r['run_id'] for r in repo.get_conversation(OWNER, 'conv-order')['runs']] == ['run-z', 'run-a']


def test_claim_serializes_turns_in_one_conversation_without_blocking_others(tmp_path):
    app = _app(tmp_path)
    repo = _catalog(app, tmp_path)
    for conv in ('conv-a', 'conv-b'):
        repo.create_conversation(OWNER, conv, title='', workspace_id='home')
    for conv, run, now in [('conv-a', 'first', 1), ('conv-a', 'second', 2), ('conv-b', 'other', 3)]:
        repo.append_turn(OWNER, conv, 'msg-' + run, run, text=run, client_token=run,
                         config_snapshot={}, now=now)
    first = repo.claim_run(OWNER, worker_id='a', now=10, lease_s=30)
    assert first['run_id'] == 'first'
    assert repo.claim_run(OWNER, worker_id='b', now=11, lease_s=30)['run_id'] == 'other'
    assert repo.claim_run(OWNER, worker_id='c', now=12, lease_s=30) is None
    repo.finish_run(OWNER, 'first', lease_id=first['lease_id'], worker_id='a', state='succeeded',
                    result_text='first answer', now=13)
    next_turn = repo.claim_run(OWNER, worker_id='c', now=14, lease_s=30)
    assert next_turn['run_id'] == 'second'
    assert [m['role'] for m in next_turn['messages']] == ['user', 'assistant', 'user']


def test_sandbox_worker_can_list_workspace_root_without_exec_launcher(tmp_path):
    from tools.platform.providers.base import ModelResponse

    app = _app(tmp_path, worker=True)
    _catalog(app, tmp_path)
    _queued(app)

    class Provider:
        def complete(self, messages, tools):
            if any(m['role'] == 'tool' for m in messages):
                return ModelResponse(kind='final', text='listed')
            return ModelResponse(kind='tool_call', tool='workspace.list', arguments={})

    worker = app.extensions['fleet']['services']['platform_worker']
    worker.provider_factory = lambda profile: Provider()
    assert worker.run_once(OWNER)['state'] == 'succeeded'


def test_sandbox_launcher_is_explicitly_wired_from_environment(tmp_path, monkeypatch):
    from hub import web
    import json

    launcher = ['/opt/fleet/bin/sandbox-wrapper', '--network=none']
    monkeypatch.setenv('AGENT_FLEET_PLATFORM_SANDBOX_LAUNCHER', json.dumps(launcher))
    monkeypatch.setattr(web, 'FLEET_HOME', tmp_path)
    app = web.make_app(ingest_token="test-token", platform_enabled=True, platform_worker_enabled=True)
    worker = app.extensions['fleet']['services']['platform_worker']
    assert worker.sandbox_launcher == tuple(launcher)
    monkeypatch.setenv('AGENT_FLEET_PLATFORM_SANDBOX_LAUNCHER', 'plain host shell')
    with pytest.raises(ValueError, match='JSON argv list'):
        web.make_app(ingest_token="test-token", platform_enabled=True, platform_worker_enabled=True)
    with pytest.raises(ValueError, match='argv list'):
        FleetConfig.from_root(tmp_path, platform_sandbox_launcher='sh')
