from hub.bootstrap import create_app
from hub.config import FleetConfig
from tools.platform.assistant_worker import AssistantWorker, PersistentAssistantWorker
from tools.platform.backends.directory import DirectoryBackend
from tools.platform.providers.compatible import DeterministicProvider
from tools.platform.runtime.base import RuntimeLimits
from tools.platform.runtime.native import NativeAssistantRuntime
from tools.platform.resource_lease import ResourceLeaseManager
from tools.platform.tool_broker import ToolBroker


def test_native_runtime_performs_one_tool_then_final_response(tmp_path):
    backend = DirectoryBackend(tmp_path / "workspace")
    leases = ResourceLeaseManager()
    lease = leases.acquire("workspace-1", "run-1")
    broker = ToolBroker(backend, leases, resource_id="workspace-1")
    runtime = NativeAssistantRuntime(DeterministicProvider(), broker, limits=RuntimeLimits(max_steps=3))
    result = runtime.run(run_id="run-1", owner_id="run-1", epoch=lease["epoch"], messages=[{"role": "user", "content": "write"}], tools=[{"name": "workspace.write"}])
    assert result.state == "succeeded"
    assert result.steps == 2
    assert (tmp_path / "workspace" / "assistant-report.md").read_text() == "Generated by the assistant.\n"


def test_runtime_enforces_step_budget(tmp_path):
    class EndlessProvider:
        def complete(self, messages, tools, *, request_observer=None):
            from tools.platform.providers.base import ModelResponse
            return ModelResponse(kind="tool_call", tool="workspace.list", arguments={})
    backend = DirectoryBackend(tmp_path / "workspace")
    leases = ResourceLeaseManager()
    lease = leases.acquire("workspace-1", "run-1")
    broker = ToolBroker(backend, leases, resource_id="workspace-1")
    result = NativeAssistantRuntime(EndlessProvider(), broker, limits=RuntimeLimits(max_steps=2)).run(run_id="run-1", owner_id="run-1", epoch=lease["epoch"], messages=[], tools=[])
    assert result.state == "failed"
    assert result.steps == 2


def test_runtime_preserves_structured_tool_call_context_for_next_model_step(tmp_path):
    class Provider:
        def __init__(self):
            self.calls = []

        def complete(self, messages, tools, *, request_observer=None):
            self.calls.append(messages)
            from tools.platform.providers.base import ModelResponse
            if len(self.calls) == 1:
                return ModelResponse(
                    kind="tool_call", tool="workspace.list", arguments={},
                    tool_call_id="call-1")
            return ModelResponse(kind="final", text="done")

    provider = Provider()
    backend = DirectoryBackend(tmp_path / "workspace")
    leases = ResourceLeaseManager()
    lease = leases.acquire("workspace-1", "run-1")
    broker = ToolBroker(backend, leases, resource_id="workspace-1")
    result = NativeAssistantRuntime(provider, broker).run(
        run_id="run-1", owner_id="run-1", epoch=lease["epoch"], messages=[], tools=[])
    assert result.state == "succeeded"
    assert provider.calls[1][-2]["role"] == "assistant"
    assert provider.calls[1][-2]["tool_calls"][0]["id"] == "call-1"
    assert provider.calls[1][-1]["role"] == "tool"
    assert provider.calls[1][-1]["tool_call_id"] == "call-1"


def test_worker_emits_bounded_run_events(tmp_path):
    backend = DirectoryBackend(tmp_path / "workspace")
    leases = ResourceLeaseManager()
    lease = leases.acquire("workspace-1", "run-1")
    broker = ToolBroker(backend, leases, resource_id="workspace-1")
    events = []
    worker = AssistantWorker(NativeAssistantRuntime(DeterministicProvider(), broker), lambda kind, payload: events.append((kind, payload)))
    result = worker.execute(run_id="run-1", owner_id="run-1", epoch=lease["epoch"], messages=[], tools=[])
    assert result.state == "succeeded"
    assert [kind for kind, _ in events] == ["run_started", "provider_request_started", "provider_request_finished", "tool_call", "tool_result", "provider_request_started", "provider_request_finished", "run_finished"]


def test_persistent_worker_updates_run_and_journals_events(tmp_path):
    app = create_app(FleetConfig.from_root(tmp_path, ingest_token="x", dev_operator="owner@example.test", platform_enabled=True))
    client = app.test_client()
    conversation = client.post("/api/platform/v1/conversations", json={}).get_json()["conversation"]
    run = client.post(f"/api/platform/v1/conversations/{conversation['conversation_id']}/turns", json={"text": "write", "client_token": "worker-1"}).get_json()["run"]
    workspace = tmp_path / "workspace"
    leases = ResourceLeaseManager()
    lease = leases.acquire("workspace-1", "owner@example.test")
    broker = ToolBroker(DirectoryBackend(workspace), leases, resource_id="workspace-1")
    worker = PersistentAssistantWorker(
        NativeAssistantRuntime(DeterministicProvider(), broker),
        app.extensions["fleet"]["services"]["run_events"],
    )
    result = worker.execute(run_id=run["run_id"], owner_id="owner@example.test", epoch=lease["epoch"], messages=[], tools=[])
    assert result.state == "succeeded"
    assert client.get(f"/api/platform/v1/runs/{run['run_id']}").get_json()["state"] == "succeeded"
    events = client.get(f"/api/platform/v1/runs/{run['run_id']}/events").get_json()["events"]
    assert [event["kind"] for event in events] == ["run_started", "provider_request_started", "provider_request_finished", "tool_call", "tool_result", "provider_request_started", "provider_request_finished", "run_finished"]


def test_run_events_are_private_cursorable_and_owner_scoped(tmp_path):
    app = create_app(FleetConfig.from_root(tmp_path, ingest_token="x", dev_operator="owner@example.test", platform_enabled=True))
    client = app.test_client()
    conversation = client.post("/api/platform/v1/conversations", json={}).get_json()["conversation"]
    run = client.post(f"/api/platform/v1/conversations/{conversation['conversation_id']}/turns", json={"text": "x", "client_token": "event-1"}).get_json()["run"]
    service = app.extensions["fleet"]["services"]["run_events"]
    service.append("owner@example.test", run["run_id"], "run_started", {"state": "running"})
    service.append("owner@example.test", run["run_id"], "run_finished", {"state": "succeeded"})
    response = client.get(f"/api/platform/v1/runs/{run['run_id']}/events?after=0")
    assert response.status_code == 200
    payload = response.get_json()
    assert [event["sequence"] for event in payload["events"]] == [1, 2]
    assert client.get(f"/api/platform/v1/runs/{run['run_id']}/events?after=1").get_json()["events"][0]["sequence"] == 2
