"""Deterministic compatible provider used for local contract tests."""
from __future__ import annotations

from .base import ModelResponse
from .observation import RequestObservation
from tools.platform.request_metadata import normalized_tokens


class DeterministicProvider:
    """A finite fake provider, never a claim of universal API compatibility."""
    def __init__(self, *, tool_name: str = "workspace.write"):
        self.tool_name = tool_name
        self.calls = 0

    def complete(self, messages, tools, *, request_observer=None):
        observation = RequestObservation(request_observer, model='deterministic', provider='deterministic')
        result = self._complete(messages, tools)
        observation.finish(metadata={'usage': normalized_tokens(result.usage)})
        return result

    def _complete(self, messages, tools):
        self.calls += 1
        if self.calls == 1:
            return ModelResponse(
                kind="tool_call", tool=self.tool_name,
                arguments={"path": "assistant-report.md", "content": "Generated by the assistant.\n"},
                usage={"input_tokens": 10, "output_tokens": 8},
            )
        return ModelResponse(
            kind="final",
            text="已完成工作区报告。",
            usage={"input_tokens": 12, "output_tokens": 8},
        )


__all__ = ["DeterministicProvider"]
